### PR TITLE
CMake Build System

### PR DESCRIPTION
**Pull request by Manuzor**
Try it out and tell me, whether the correct solution and projects are generated. It compiled on my machine.

I made it specific to python3.5 for now. Extending it is straight forward but will make the CMake code ugly. Not that CMake code ever looks pretty...

It should also find the python directory automagically, if it is in your `$PATH`.

If everything works, you can delete your manually created visual studio stuff.

### CODE REVIEW

**Comment by pampersrocker** [comment]
Compilation works fine, however you need to copy the python dll manually for the PyBindTest.
Is there an easy way to copy the dll with cmake, or is this something more complex?

**Comment by Manuzor** [comment]
Well, if python is in your `$PATH` you won't need to copy the DLLs, unless they're in a subdirectory (like `<python-dir>/DLLs/sqlite.dll`).

**Comment by Manuzor** [comment]
I will alter PyBind to compile like the rest of lab132, i.e. with `-debug` suffix to a top-level `bin/` and `lib` folder. This will make stuff easier for us later on in terms of integration.

**Comment by pampersrocker** [comment]
Ah k, I've just installed python 3.5 and it was not yet in my path. now everything works.

**Comment by Manuzor** [comment]
By the way, since CMake is such an awesome piece of software, header-only libraries have to be treated specially. And I don't mean something like `set(HEADER_ONLY ON/OFF)`. So, as soon as `PyBind` itself has any `.cpp` files, we'll have to adjust the `CMakeLists.txt` file again. Isn't that awesome? :+1:

**Pull request merged**
